spring:
  application:
    name: recorder
  threads:
    virtual:
      enabled: true

logging:
  level:
    com.dm4nk.monitoring.logtrace: info

logger:
  enabled: true

logtrace:
  enabled: true
  before-message-prefix: '['
  after-message-prefix: '['

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
